services:
  - type: web
    name: copymate-server
    runtime: node
    rootDir: shared-clipboard/server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        generateValue: false